// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5USwdxDqPz6c8oMMLCf1uH4fdZ3G4n-4',
    appId: '1:485744389634:web:aaa353f13659a9b0a8811b',
    messagingSenderId: '485744389634',
    projectId: 'crossword-tester',
    authDomain: 'crossword-tester.firebaseapp.com',
    storageBucket: 'crossword-tester.appspot.com',
    measurementId: 'G-9MQGGCY5NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-8wBJrL6Sz0ZbJMpm_cgu7m5I-hLOabE',
    appId: '1:485744389634:android:f4657125a1e7c408a8811b',
    messagingSenderId: '485744389634',
    projectId: 'crossword-tester',
    storageBucket: 'crossword-tester.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYGNIrGvfrKilB5KtYxh0Jx3Lcw7G8Pns',
    appId: '1:485744389634:ios:0e864123ff586433a8811b',
    messagingSenderId: '485744389634',
    projectId: 'crossword-tester',
    storageBucket: 'crossword-tester.appspot.com',
    iosClientId: '485744389634-p4366m4hc181g43heh5c75ak8oek6ng9.apps.googleusercontent.com',
    iosBundleId: 'ru.kapkekes.cts',
  );
}
